#!/usr/bin/env bash
#-----------------------------------------------------
#Script:
#
#Descrição: Testa se o comando é builtin ou não
#
#Versão	  :0.1
#Autor    : Hélio Rodrigues
#Data     : 
#Licença  : GNU/GPL v3.0
#-----------------------------------------------------
#Uso      : ./builtin
#-----------------------------------------------------

# Testa se foi passado um argumento
msg="É preciso informar um único nome de comando válido"
test $# -ne 1 && echo $msg && exit 1

#Executa "help" para verificar se vai conseguir
#mostrar a ajuda do comando (sucesso) ou não (erro)

help $1 &> /dev/null

#Usar comando "test" para avaliar a expressão...

test $? -eq 0 && echo "É builtin!" || echo "Não é builtin... :-("

exit 0
